In [76]:
from numpy import * 
import numpy as np

num_movies = 10
num_users = 5
ratings = array([[8, 4, 0, 0, 4], [0, 0, 8, 10, 4], [8, 10, 0, 0, 6], [10, 10, 8, 10, 10], [0, 0, 0, 0, 0], [2, 0, 4, 0, 6], [8, 6, 4, 0, 0], [0, 0, 6, 4, 0], [0, 6, 0, 4, 10], [0, 4, 6, 8, 8]])

# ratings = random.randint(11, size = (num_movies, num_users))
print ratings
print ratings_mean
print ratings_norm
print ratings.shape



[[ 8  4  0  0  4]
 [ 0  0  8 10  4]
 [ 8 10  0  0  6]
 [10 10  8 10 10]
 [ 0  0  0  0  0]
 [ 2  0  4  0  6]
 [ 8  6  4  0  0]
 [ 0  0  6  4  0]
 [ 0  6  0  4 10]
 [ 0  4  6  8  8]]
[ 5.     2.75   3.     6.     2.625  1.5    2.25   2.375  2.5    3.25 ]
[[ 3.     3.     3.     3.    -1.    -5.    -5.    -1.   ]
 [-2.75  -2.75  -2.75  -2.75  -2.75   5.25   7.25   1.25 ]
 [-3.    -3.    -3.     5.     7.    -3.    -3.     3.   ]
 [-6.    -6.    -6.     4.     4.     2.     4.     4.   ]
 [ 4.375  4.375  4.375 -2.625 -2.625 -2.625 -2.625 -2.625]
 [-1.5   -1.5   -1.5    0.5   -1.5    2.5   -1.5    4.5  ]
 [-2.25  -2.25  -2.25   5.75   3.75   1.75  -2.25  -2.25 ]
 [ 0.625  0.625  0.625 -2.375 -2.375  3.625  1.625 -2.375]
 [-2.5   -2.5   -2.5   -2.5    3.5   -2.5    1.5    7.5  ]
 [-3.25  -3.25  -3.25  -3.25   0.75   2.75   4.75   4.75 ]]
(10, 5)


In [77]:
did_rate = (ratings != 0) * 1
print did_rate

[[1 1 0 0 1]
 [0 0 1 1 1]
 [1 1 0 0 1]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [1 0 1 0 1]
 [1 1 1 0 0]
 [0 0 1 1 0]
 [0 1 0 1 1]
 [0 1 1 1 1]]


In [78]:
h_ratings = zeros((num_movies, 1))

print h_ratings

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [79]:
h_ratings[0] = 8 #action
h_ratings[4] = 7 #comedy
h_ratings[7] = 3 #disney comedy

print h_ratings

[[ 8.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 7.]
 [ 0.]
 [ 0.]
 [ 3.]
 [ 0.]
 [ 0.]]


In [80]:
ratings = append(h_ratings, ratings, axis = 1)
did_rate = append(((h_ratings != 0) * 1), did_rate, axis = 1)

ratings_mean = np.nanmean(ratings, axis=1).T
ratings_norm = (ratings.T - ratings_mean).T
# ratings = random.randint(11, size = (num_movies, num_users))
print ratings.shape
# print ratings_mean
# print ratings_norm
print did_rate.shape


(10, 6)
(10, 6)


In [81]:
num_users = ratings.shape[1]
num_features = 3

In [82]:
#Initialise the parameters for regression
movie_features = random.randn( num_movies, num_features )
user_prefs = random.randn( num_users, num_features )
initial_X_and_theta = r_[movie_features.T.flatten(), user_prefs.T.flatten()]

print movie_features 
print user_prefs 


[[ 0.12330987  0.43795216  0.54186158]
 [-0.57431133  1.17152212  1.62330788]
 [ 1.86699544 -1.39732947  0.1088634 ]
 [ 0.6073384   0.9723796   0.77424076]
 [ 0.12545146 -0.63454091  0.33647248]
 [-0.95630754 -0.00583809 -2.01144224]
 [ 0.17492657 -0.46688015 -0.99929244]
 [ 1.43256433 -0.1779201   0.44897165]
 [-0.19414448  0.5669478  -0.33792468]
 [ 0.18370966  0.26128612  0.34549596]]
[[-0.65193915  0.06587106 -2.12215142]
 [-0.00766119  0.00359572  0.14351648]
 [ 0.01356211 -1.08425635 -0.64348479]
 [-0.80881325  1.32544083 -0.98841668]
 [ 0.11810692  0.23406089 -0.6585429 ]
 [-0.03402813 -0.07235331 -0.1597926 ]]


In [83]:
print initial_X_and_theta


[ 0.12330987 -0.57431133  1.86699544  0.6073384   0.12545146 -0.95630754
  0.17492657  1.43256433 -0.19414448  0.18370966  0.43795216  1.17152212
 -1.39732947  0.9723796  -0.63454091 -0.00583809 -0.46688015 -0.1779201
  0.5669478   0.26128612  0.54186158  1.62330788  0.1088634   0.77424076
  0.33647248 -2.01144224 -0.99929244  0.44897165 -0.33792468  0.34549596
 -0.65193915 -0.00766119  0.01356211 -0.80881325  0.11810692 -0.03402813
  0.06587106  0.00359572 -1.08425635  1.32544083  0.23406089 -0.07235331
 -2.12215142  0.14351648 -0.64348479 -0.98841668 -0.6585429  -0.1597926 ]


In [84]:
initial_X_and_theta.shape


(48,)

In [85]:
def unroll_params(X_and_theta, num_users, num_movies, num_features):
    first_30 = X_and_theta[:num_movies * num_features]
    X = first_30.reshape((num_features, num_movies)).T
    last18 = X_and_theta[num_movies * num_features:]
    theta = last18.reshape(num_features, num_users).T
    return X, theta


In [91]:
def calculate_gradient(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
    X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
    difference = X.dot(theta.T) * did_rate - ratings
    X_grad = difference.dot(theta) + reg_param * X
    theta_grad = difference.T.dot(X) + reg_param * theta
    
    return r_[X_grad.T.flatten(), theta_grad.T.flatten()]



In [92]:
def calculate_cost(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):

    cost = sum( (X.dot( theta.T ) * did_rate - ratings) ** 2 ) / 2
    regularization = (reg_param / 2) * (sum( theta**2 ) + sum(X**2))
    return cost + regularization

In [93]:
print did_rate.shape
print ratings.shape
print X.shape
print theta.shape

# X,theta = unroll_params(initial_X_and_theta, num_users, num_movies, num_features)
# difference = X.dot(theta.T) * did_rate - ratings
# # r_ = calculate_gradient(initial_X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param)
# # calculate_cost(initial_X_and_theta, ratings, did_rate, num_users, num_movies, num_features, 30)

from scipy import optimize

reg_param = 30 

minimized_cost_and_optimal_params = optimize.fmin_cg(calculate_cost, fprime=calculate_gradient, x0=initial_X_and_theta, args=(ratings, did_rate, num_users, num_movies, num_features, reg_param), maxiter=100, disp=True, full_output=True ) 
# print X
# print X.shape

print did_rate.shape

(10, 6)
(10, 6)
(10, 3)
(6, 3)
         Current function value: 1339.957880
         Iterations: 0
         Function evaluations: 31
         Gradient evaluations: 19
(10, 6)


In [94]:
# cost, optimal_movie_features_and_user_prefs = minimized_cost_and_optimal_params[1], minimized_cost_and_optimal_params[0]
print theta

[[-0.65193915  0.06587106 -2.12215142]
 [-0.00766119  0.00359572  0.14351648]
 [ 0.01356211 -1.08425635 -0.64348479]
 [-0.80881325  1.32544083 -0.98841668]
 [ 0.11810692  0.23406089 -0.6585429 ]
 [-0.03402813 -0.07235331 -0.1597926 ]]


In [95]:
print theta.shape

(6, 3)


In [98]:
cost, optimal_movie_features_and_user_prefs = minimized_cost_and_optimal_params[1], minimized_cost_and_optimal_params[0]


In [99]:
movie_features, user_prefs = unroll_params(optimal_movie_features_and_user_prefs, num_users, num_movies, num_features)


In [100]:
print movie_features
print user_prefs
all_predictions = movie_features.dot( user_prefs.T )
print all_predictions
predictions_for_harsha = all_predictions[:, 0:1] + ratings_mean
print predictions_for_harsha
print h_ratings


[[ 0.12330987  0.43795216  0.54186158]
 [-0.57431133  1.17152212  1.62330788]
 [ 1.86699544 -1.39732947  0.1088634 ]
 [ 0.6073384   0.9723796   0.77424076]
 [ 0.12545146 -0.63454091  0.33647248]
 [-0.95630754 -0.00583809 -2.01144224]
 [ 0.17492657 -0.46688015 -0.99929244]
 [ 1.43256433 -0.1779201   0.44897165]
 [-0.19414448  0.5669478  -0.33792468]
 [ 0.18370966  0.26128612  0.34549596]]
[[-0.65193915  0.06587106 -2.12215142]
 [-0.00766119  0.00359572  0.14351648]
 [ 0.01356211 -1.08425635 -0.64348479]
 [-0.80881325  1.32544083 -0.98841668]
 [ 0.11810692  0.23406089 -0.6585429 ]
 [-0.03402813 -0.07235331 -0.1597926 ]]
[[ -1.20145448e+00   7.83961221e-02  -8.21859750e-01  -5.48400085e-02
   -2.39767874e-01  -1.22468761e-01]
 [ -2.99331967e+00   2.41583811e-01  -2.32259310e+00   4.12789291e-01
   -8.62640503e-01  -3.24613339e-01]
 [ -1.54023561e+00  -3.70411226e-03   1.47033180e+00  -3.46973057e+00
   -1.78246321e-01   2.01754732e-02]
 [ -1.97495211e+00   1.09959782e-01  -1.54428412e+00 